kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    app: prometheus-server
  name: prom-data-pvc
  namespace: monitoirng
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data"
