apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-server
  name: prom-data-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostPath
